### ISSUE TITLE
fireRegimePolys: is it a list, an SPDF, sf, or quosure???

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/scfm#25]
`scfmDriver`, `scfmRegime` and `scfmLandcoverInit` disagree about what typo of object this should be.

1. `scfmDriver` expects SPDF (according to metadata and the use of `rgeos::gArea()`;
2. `scfmRegime` uses `sf` functions throughout but metadata says SPDF;
3. `scfmLandcoverInit` uses `sf` functions (and I recently updated te metadat accordingly).

@ianmseddy do you have any unpushed changes?

**Comment by ianmseddy** [comment]
I don't have any unpushed changes. `scfm` should be using sf for studyArea and fireRegimePolys. Driver will run with that - if it isn't, it's an error. I see the issue - I haven't tested in parallel before, and that's where the `rgeos` function is.

**Comment by achubaty** [comment]
i pushed updates for this. still needs more testing, especially the parallel bit.

also need to figure out the quosure part.

**Comment by achubaty** [comment]
there's an `if` block that checks for a quosure. not sure how/why it would be one though

**Comment by achubaty** [comment]
`fireRegimePolys` is now `sf` throughout. will confirm the use of quosure as functions moved to `scfmutils` package and modules all updated.
